#!/usr/bin/env node
const shell = require('shelljs');

function command(cmd) {
  if (shell.exec(cmd).code !== 0) {
    shell.echo(`Error: ${cmd}`);
    shell.exit(1);
  }
}

/** 命令行的所有参数 */
const options = {};
const argv = process.argv.slice(2);
argv.forEach(row => {
  const keyVal = row.split('=');
  const [key, value] = keyVal;
  options[key] = value || null;
});


const splitLine = '==================================';
const now = new Date().getTime();

function testDeploy() {
  shell.echo(splitLine);
  shell.echo('Testing deploy:');
  shell.echo(splitLine);
  command('npm run test');
  shell.echo('copy to test server');
  shell.echo(splitLine);
  command('scp -r dist/*  root@10.20.129.28:/home/miracle/oilhui/dist');
  command('rm ./dist -rf');
  shell.echo('TECH_TEST_ENV Deployed!');
}

function YwTestDeploy() {
  shell.echo(splitLine);
  shell.echo('YwTesting deploy:');
  shell.echo(splitLine);
  shell.echo('Start Shift YWTEST_Env URL');
  shell.echo(splitLine);   
  command('npm run appendyw');
  shell.echo(splitLine);   
  shell.echo('End Shift YWTEST_Env URL');
  shell.echo(splitLine);    
  command('npm run ywtest');
  shell.echo('copy to ywtest server');
  shell.echo(splitLine);
  command('scp -r dist/*  root@10.20.129.28:/home/miracle-test/oilhui/dist');
  command('rm ./dist -rf');
  command('git checkout public/index.html');
  shell.echo('YW_TEST_ENV Deployed!');
}



function testZipDeploy() {
  const zipName = `oilback_test_${now}.zip`;
  shell.echo(splitLine);
  shell.echo('Testing zip deploy:');
  shell.echo(splitLine);
  command('npm run test');
  shell.echo(`zip to ${zipName}`);
  shell.echo(splitLine);
  command(`zip -m -r -q ${zipName} ./dist`);
  shell.echo('TEST_ZIP_ENV Deployed!');
}

function proZipDeploy() {
  const zipName = 'oilhui.zip';
  shell.echo(splitLine);
  shell.echo('Start Shift Pro_Env URL');
  shell.echo(splitLine);   
  command('npm run append');
  shell.echo('End Shift Pro_Env URL');
  shell.echo(splitLine);    
  shell.echo('production zip deploy:');
  shell.echo(splitLine);
  command('npm run pro');
  shell.echo(`zip to ${zipName}`);
  shell.echo(splitLine);
  command(`zip -m -r -q ${zipName} ./dist`);
  command(`scp ${zipName}  share@192.168.4.16:/home/share/front/`);  
  command('git checkout public/index.html');
  shell.echo('PRODUCTION_ZIP_ENV Deployed!');
}

if (options.t !== undefined) {
  testDeploy();
  return;
}

if (options.y !== undefined) {
  YwTestDeploy();
  return;
}

if (options.tz !== undefined) {
  testZipDeploy();
  return;
}

if (options.pz !== undefined) {
  proZipDeploy();
  return;
}

if (options.a !== undefined) {
  return;
}

